### ISSUE TITLE
Infer the chain-id from provider URL

### ISSUE THREAD

**Issue by zemse** [axiom-crypto/axiom-sdk#4]
https://docs.axiom.xyz/developers/troubleshooting#provider-uris

chain id can be kept unknown during config time. and later in an async function it could be resolved to its true value. chain id can still be taken as optional for keeping backward compatibility.

also, is this repo open to external contributions PRs?

**Comment by jonathanpwang** [comment]
In this case we were thinking `chainId` is an extra safeguard to ensure you're cognizant of which chain you're about to query, since often `PROVIDER_URI` is in some `.env` and can be easily forgotten.

But in general, we are open to external contributions (subject to review from the team) :)

**Comment by zemse** [comment]
That is true and worth sanity-checking. But often ethers provider and others would provide a DX where the dev provides minimal config (like just URL in this case). Still, they can optionally provide more details which could be derived but for extra sanity checks. Maybe chain id can be optional and perform a check if URL and chain id do not match. Not a big deal, but just saves a google/duckduckgo search (if dev does not remember chain id for that chain).

**Comment by jonathanpwang** [comment]
True - how about if either chainId = 1 or provider's chainId is 1, then we enforce chainId must be provided and do the sanity check? Otherwise it's optional sanity check as you suggested.

**Comment by zemse** [comment]
sure, i'll try creating a PR!

**Comment by ytham** [comment]
Will close this for now; we're planning on adding some backup functionality for providers. With quicknode, there's unfortunately not a straightforward way to get the chain ID from the provider URI.
